[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.obj.deals"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "deals", "automation"] 
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.deals"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
