[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.obj.deals"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["deals", "automation", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.deals"

[build-options]
observabilityIncluded = true
